import * as z from "zod";
export const LoginSchema = z.object({
  gmail: z.string().email({
    message: "Gmail is required",
  }),
  password: z.string().min(1, { message: "Password is required" }),
  // callbackUrl: z.string(),
});

export const ResetSchema1 = z.object({
  gmail: z.string().email({
    message: "Gmail is required",
  }),
});
export const ResetSchema2 = z.object({
  otp: z.number().min(6, {
    message: "Minimum 6 digits required",
  }),
});

export const RegisterSchema = z.object({
  gmail: z.string().email({
    message: "Gmail is required",
  }),
  password: z.string().min(6, { message: "Minimum 6 characters required" }),
  name: z.string().min(1, {
    message: "Name is required",
  }),
  country: z.boolean(),
  // otp: z.number().min(6, {
  //   message: "Minimum 6 digits required",
  // }),
  // type: z.string().min(1, {
  //   message: "type is required",
  // }),
});
export const QuerySchema = z.object({
  email: z.string().email({
    message: "Gmail is required",
  }),
  name: z.string().min(1, {
    message: "Name is required",
  }),
  city: z.string().min(1, { message: "City required" }),
  phone: z.string().min(10, {
    message: "Enter valid value",
  }),
  requirement: z.string().min(1, {
    message: "Required",
  }),
});
export const QuerySchema2 = z.object({
  email: z.string().min(0),
  name: z.string().min(0, {
    message: "Name is required",
  }),
  city: z.string().min(0, { message: "City required" }),
  phone: z.string().min(0, {
    message: "Enter valid value",
  }),
  requirement: z.string().min(0, {
    message: "Required",
  }),
});

export const CreateJobSchema = z.object({
  specifications: z.string().min(6, {
    message: "Minimum 6 letters required",
  }),
  floors: z.number().min(0, {
    message: "If you do not want this field enter 0",
  }),
  area: z.string().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  A: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  B: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  C: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  D: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  E: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  D1: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  D2: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  D3: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  D4: z.number().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  direction: z.string().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  plot: z.string().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  type: z.string().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  expected: z.string().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  studentPrice: z.string().min(0, {
    message: "Enter 0 if you do not want this field",
  }),
  drawing: z.string(),
});

export const OtpVerifySchema = z.object({
  otp: z.number().min(6, {
    message: "Minimum 6 digits required",
  }),
});

export const OtpFormSchema = z.object({
  gmail: z.string().email({
    message: "Gmail is required",
  }),
  password: z.string().min(6, { message: "Minimum 6 characters required" }),
  name: z.string().min(1, {
    message: "Name is required",
  }),
  type: z.string().min(1, {
    message: "type is required",
  }),
  Proof: z.string().min(2, {
    message: "This field is required",
  }),
  Phone: z.string().min(10, {
    message: "Enter valid value",
  }),
  country: z.boolean(),
  paymentId: z.string().min(7, {
    message: "Enter valid value",
  }),
});

export const RectanglePlotSchema = z.object({
  A: z.number().min(0, {
    message: "Enter valid value",
  }),
  B: z.number().min(0, {
    message: "Enter valid value",
  }),
  C: z.number().min(0, {
    message: "Enter valid value",
  }),
  D: z.number().min(0, {
    message: "Enter valid value",
  }),
  floor: z.number().min(2, {
    message: "minimum value:2(Ground +1)",
  }),
  drawing: z.string(),
  specifications: z.string(),
  direction: z.string(),
  phone: z.string(),
});

export const TrapiziumPlotSchema = z.object({
  A: z.number().min(0, {
    message: "Enter valid value",
  }),
  B: z.number().min(0, {
    message: "Enter valid value",
  }),
  C: z.number().min(0, {
    message: "Enter valid value",
  }),
  D: z.number().min(0, {
    message: "Enter valid value",
  }),
  D1: z.number().min(0, {
    message: "Enter valid value",
  }),
  D2: z.number().min(0, {
    message: "Enter valid value",
  }),
  floor: z.number().min(0, {
    message: "minimum value:2(Ground +1)",
  }),
  drawing: z.string().min(0, {
    message: "Enter valid value",
  }),
  specifications: z.string().min(0, {
    message: "Enter valid value",
  }),
  direction: z.string(),
  phone: z.string(),
});
export const PentaPlotSchema = z.object({
  A: z.number().min(0, {
    message: "Enter valid value",
  }),
  B: z.number().min(0, {
    message: "Enter valid value",
  }),
  C: z.number().min(0, {
    message: "Enter valid value",
  }),
  D: z.number().min(0, {
    message: "Enter valid value",
  }),
  E: z.number().min(0, {
    message: "Enter valid value",
  }),
  D1: z.number().min(0, {
    message: "Enter valid value",
  }),
  D2: z.number().min(0, {
    message: "Enter valid value",
  }),
  D3: z.number().min(0, {
    message: "Enter valid value",
  }),
  D4: z.number().min(0, {
    message: "Enter valid value",
  }),
  floor: z.number().min(2, {
    message: "minimum value:2(Ground +1)",
  }),
  drawing: z.string(),
  specifications: z.string(),
  direction: z.string(),
  phone: z.string(),
});

export const areaList = {
  type1: "1400",
  type2: "2800",
  type3: "4000",
  type4: "5400",
  type5: "1400",
  type6: "2800",
  type7: "5400",
  type8: "10890",
  type9: "16335",
  type10: "21780",
  type11: "27225",
  type12: "10",
};
export const areaPlans = [
  {
    pack: "Basic",
    inr: "5499",
    features: "Layout Plan",
    floors: 2,
    type: "type1",
    dollar: "",
    area: "1400",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "54999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type1",
    dollar: "",
    area: "1400",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "6999",
    features: "Layout Plan",
    floors: 3,
    type: "type1",
    dollar: "",
    area: "1400",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "65999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type1",
    dollar: "",
    area: "1400",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "7999",
    features: "Layout Plan",
    floors: 4,
    type: "type1",
    dollar: "",
    area: "1400",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "77999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type1",
    dollar: "",
    area: "1400",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "8999",
    features: "Layout Plan",
    floors: 5,
    type: "type1",
    dollar: "",
    area: "1400",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "88999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type1",
    dollar: "",
    area: "1400",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "8999",
    features: "Layout Plan",
    floors: 2,
    type: "type2",
    dollar: "",
    area: "2800",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "64999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type2",
    dollar: "",
    area: "2800",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "9999",
    features: "Layout Plan",
    floors: 3,
    type: "type2",
    dollar: "",
    area: "2800",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "75999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type2",
    dollar: "",
    area: "2800",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "10999",
    features: "Layout Plan",
    floors: 4,
    type: "type2",
    dollar: "",
    area: "2800",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "87999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type2",
    dollar: "",
    area: "2800",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "16999",
    features: "Layout Plan",
    floors: 5,
    type: "type2",
    dollar: "",
    area: "2800",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "98999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type2",
    dollar: "",
    area: "2800",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "15999",
    features: "Layout Plan",
    floors: 2,
    type: "type3",
    dollar: "",
    area: "4000",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "75999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type3",
    dollar: "",
    area: "4000",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "16999",
    features: "Layout Plan",
    floors: 3,
    type: "type3",
    dollar: "",
    area: "4000",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "87999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type3",
    dollar: "",
    area: "4000",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "17999",
    features: "Layout Plan",
    floors: 4,
    type: "type3",
    dollar: "",
    area: "4000",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "98999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type3",
    dollar: "",
    area: "4000",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "18999",
    features: "Layout Plan",
    floors: 5,
    type: "type3",
    dollar: "",
    area: "4000",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "109999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type3",
    dollar: "",
    area: "4000",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "17999",
    features: "Layout Plan",
    floors: 2,
    type: "type4",
    dollar: "",
    area: "5400",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "87999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type4",
    dollar: "",
    area: "5400",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "19599",
    features: "Layout Plan",
    floors: 3,
    type: "type4",
    dollar: "",
    area: "5400",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "98999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type4",
    dollar: "",
    area: "5400",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "20599",
    features: "Layout Plan",
    floors: 4,
    type: "type4",
    dollar: "",
    area: "5400",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "109999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type4",
    dollar: "",
    area: "5400",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "21599",
    features: "Layout Plan",
    floors: 5,
    type: "type4",
    dollar: "",
    area: "5400",
    plan: "Residential",
  },
  {
    pack: "Full",
    inr: "119999",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type4",
    dollar: "",
    area: "5400",
    plan: "Residential",
  },
  {
    pack: "Basic",
    inr: "13999",
    features: "Layout Plan",
    floors: 2,
    type: "type5",
    dollar: "",
    area: "1400",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "110000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type5",
    dollar: "",
    area: "1400",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "14599",
    features: "Layout Plan",
    floors: 3,
    type: "type5",
    dollar: "",
    area: "1400",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "120000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type5",
    dollar: "",
    area: "1400",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "15599",
    features: "Layout Plan",
    floors: 4,
    type: "type5",
    dollar: "",
    area: "1400",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "130000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type5",
    dollar: "",
    area: "1400",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "16599",
    features: "Layout Plan",
    floors: 5,
    type: "type5",
    dollar: "",
    area: "1400",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "140000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type5",
    dollar: "",
    area: "1400",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "21999",
    features: "Layout Plan",
    floors: 2,
    type: "type6",
    dollar: "",
    area: "2800",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "250000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type6",
    dollar: "",
    area: "2800",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "22599",
    features: "Layout Plan",
    floors: 3,
    type: "type6",
    dollar: "",
    area: "2800",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "260000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type6",
    dollar: "",
    area: "2800",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "23599",
    features: "Layout Plan",
    floors: 4,
    type: "type6",
    dollar: "",
    area: "2800",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "270000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type6",
    dollar: "",
    area: "2800",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "24599",
    features: "Layout Plan",
    floors: 5,
    type: "type6",
    dollar: "",
    area: "2800",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "280000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type6",
    dollar: "",
    area: "2800",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "29999",
    features: "Layout Plan",
    floors: 2,
    type: "type7",
    dollar: "",
    area: "5400",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "300000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type7",
    dollar: "",
    area: "5400",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "30999",
    features: "Layout Plan",
    floors: 3,
    type: "type7",
    dollar: "",
    area: "5400",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "310000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type7",
    dollar: "",
    area: "5400",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "31999",
    features: "Layout Plan",
    floors: 4,
    type: "type7",
    dollar: "",
    area: "5400",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "320000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type7",
    dollar: "",
    area: "5400",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "32999",
    features: "Layout Plan",
    floors: 2,
    type: "type7",
    dollar: "",
    area: "5400",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "330000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type7",
    dollar: "",
    area: "5400",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "39999",
    features: "Layout Plan",
    floors: 2,
    type: "type8",
    dollar: "",
    area: "10890",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "350000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type8",
    dollar: "",
    area: "10890",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "40999",
    features: "Layout Plan",
    floors: 3,
    type: "type8",
    dollar: "",
    area: "10890",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "360000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type8",
    dollar: "",
    area: "10890",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "41999",
    features: "Layout Plan",
    floors: 4,
    type: "type8",
    dollar: "",
    area: "10890",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "370000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type8",
    dollar: "",
    area: "10890",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "42999",
    features: "Layout Plan",
    floors: 5,
    type: "type8",
    dollar: "",
    area: "10890",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "380000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type8",
    dollar: "",
    area: "10890",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "49999",
    features: "Layout Plan",
    floors: 2,
    type: "type9",
    dollar: "",
    area: "16335",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "400000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type9",
    dollar: "",
    area: "16335",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "50999",
    features: "Layout Plan",
    floors: 3,
    type: "type9",
    dollar: "",
    area: "16335",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "410000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type9",
    dollar: "",
    area: "16335",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "51999",
    features: "Layout Plan",
    floors: 4,
    type: "type9",
    dollar: "",
    area: "16335",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "420000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type9",
    dollar: "",
    area: "16335",
    plan: "Commercial",
  },

  {
    pack: "Basic",
    inr: "52999",
    features: "Layout Plan",
    floors: 5,
    type: "type9",
    dollar: "",
    area: "16335",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "430000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type9",
    dollar: "",
    area: "16335",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "59999",
    features: "Layout Plan",
    floors: 2,
    type: "type10",
    dollar: "",
    area: "21780",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "450000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type10",
    dollar: "",
    area: "21780",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "60999",
    features: "Layout Plan",
    floors: 3,
    type: "type10",
    dollar: "",
    area: "21780",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "460000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type10",
    dollar: "",
    area: "21780",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "61999",
    features: "Layout Plan",
    floors: 4,
    type: "type11",
    dollar: "",
    area: "21780",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "470000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type10",
    dollar: "",
    area: "21780",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "62999",
    features: "Layout Plan",
    floors: 5,
    type: "type10",
    dollar: "",
    area: "21780",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "480000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type10",
    dollar: "",
    area: "21780",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "69999",
    features: "Layout Plan",
    floors: 2,
    type: "type11",
    dollar: "",
    area: "27225",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "500000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 2,
    type: "type11",
    dollar: "",
    area: "27225",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "70999",
    features: "Layout Plan",
    floors: 3,
    type: "type11",
    dollar: "",
    area: "27225",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "510000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 3,
    type: "type11",
    dollar: "",
    area: "27225",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "71999",
    features: "Layout Plan",
    floors: 4,
    type: "type11",
    dollar: "",
    area: "27225",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "520000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 4,
    type: "type11",
    dollar: "",
    area: "27225",
    plan: "Commercial",
  },
  {
    pack: "Basic",
    inr: "72999",
    features: "Layout Plan",
    floors: 5,
    type: "type11",
    dollar: "",
    area: "27225",
    plan: "Commercial",
  },
  {
    pack: "Full",
    inr: "530000",
    features:
      "Working Drawings Structure Drawings | 3D - Views | 2D - Elevations | Plumbing Drawings | Electrical Drawings | Joinery Drawings",
    floors: 5,
    type: "type11",
    dollar: "",
    area: "27225",
    plan: "Commercial",
  },
];
export const directions = [
  {
    value: "north",
    label: "North",
  },
  {
    value: "south",
    label: "South",
  },
  {
    value: "east",
    label: "East",
  },
  {
    value: "west",
    label: "West",
  },
];

export const prices = [
  {
    type: "type1",
    pack: "basic",
    floors: 2,
    price: 4999,
  },
  {
    type: "type1",
    pack: "basic",
    floors: 3,
    price: 5999,
  },
  {
    type: "type1",
    pack: "basic",
    floors: 4,
    price: 6999,
  },
  {
    type: "type1",
    pack: "basic",
    floors: 5,
    price: 7999,
  },
  {
    type: "type1",
    pack: "full",
    floors: 2,
    price: 49999,
  },
  {
    type: "type1",
    pack: "full",
    floors: 3,
    price: 59999,
  },
  {
    type: "type1",
    pack: "full",
    floors: 4,
    price: 69999,
  },
  {
    type: "type1",
    pack: "full",
    floors: 5,
    price: 79999,
  },
  {
    type: "type2",
    pack: "basic",
    floors: 2,
    price: 7999,
  },
  {
    type: "type2",
    pack: "basic",
    floors: 3,
    price: 8999,
  },
  {
    type: "type2",
    pack: "basic",
    floors: 4,
    price: 9999,
  },
  {
    type: "type2",
    pack: "basic",
    floors: 5,
    price: 10999,
  },
  {
    type: "type2",
    pack: "full",
    floors: 2,
    price: 59999,
  },
  {
    type: "type2",
    pack: "full",
    floors: 3,
    price: 69999,
  },
  {
    type: "type2",
    pack: "full",
    floors: 4,
    price: 79999,
  },
  {
    type: "type2",
    pack: "full",
    floors: 5,
    price: 89999,
  },
  {
    type: "type3",
    pack: "basic",
    floors: 2,
    price: 13999,
  },
  {
    type: "type3",
    pack: "basic",
    floors: 3,
    price: 14999,
  },
  {
    type: "type3",
    pack: "basic",
    floors: 4,
    price: 15999,
  },
  {
    type: "type3",
    pack: "basic",
    floors: 5,
    price: 16999,
  },
  {
    type: "type3",
    pack: "full",
    floors: 2,
    price: 69999,
  },
  {
    type: "type3",
    pack: "full",
    floors: 3,
    price: 79999,
  },
  {
    type: "type3",
    pack: "full",
    floors: 4,
    price: 89999,
  },
  {
    type: "type3",
    pack: "full",
    floors: 5,
    price: 99999,
  },
  {
    type: "type4",
    pack: "basic",
    floors: 2,
    price: 16999,
  },
  {
    type: "type4",
    pack: "basic",
    floors: 3,
    price: 17999,
  },
  {
    type: "type4",
    pack: "basic",
    floors: 4,
    price: 18999,
  },
  {
    type: "type4",
    pack: "basic",
    floors: 5,
    price: 19999,
  },
  {
    type: "type4",
    pack: "full",
    floors: 2,
    price: 79999,
  },
  {
    type: "type4",
    pack: "full",
    floors: 3,
    price: 89999,
  },
  {
    type: "type4",
    pack: "full",
    floors: 4,
    price: 99999,
  },
  {
    type: "type4",
    pack: "full",
    floors: 5,
    price: 109999,
  },
];
